const wordDatabase = [
    // --- Objects/Things ---
    { word: { en: "Pizza", ku: "پیتزا" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Ocean", ku: "زەریا" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Guitar", ku: "گیتار" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Hospital", ku: "نەخۆشخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "School", ku: "قوتابخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Car", ku: "ئۆتۆمبێل" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Book", ku: "کتێب" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Mountain", ku: "چیا" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Phone", ku: "تەلەفۆن" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Coffee", ku: "قاوە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },

    // --- People/Family ---
    { word: { en: "Man", ku: "پیاو" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Woman", ku: "ژن" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Child", ku: "منداڵ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Father", ku: "باوک" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Mother", ku: "دایک" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Brother", ku: "برا" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Sister", ku: "خوشک" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Friend", ku: "هاوڕێ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },

    // --- Jobs/Professions/Roles ---
    { word: { en: "Teacher", ku: "مامۆستا" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Doctor", ku: "دکتۆر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Student", ku: "قوتابی" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Baby", ku: "ساوا" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Grandfather", ku: "باپیر" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Grandmother", ku: "دایەگەورە" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Neighbor", ku: "دراوسێ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Stranger", ku: "بێگانە" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Engineer", ku: "ئەندازیار" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Pilot", ku: "فڕۆکەوان" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Soldier", ku: "سەرباز" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Cook/Chef", ku: "چێشتلێنەر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Husband", ku: "مێرد" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Wife", ku: "ژن" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Cousin (Male)", ku: "کوڕە مام / خاڵ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Uncle (Paternal)", ku: "مام" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Aunt (Maternal)", ku: "خاڵۆژن" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Boss", ku: "سەرۆک" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Politician", ku: "سیاسەتمەدار" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Journalist", ku: "ڕۆژنامەنووس" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Waiter", ku: "خزمەتکار" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Athlete", ku: "وەرزشکار" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Artist/Painter", ku: "هونەرمەند" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Lawyer", ku: "پارێزەر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Firefighter", ku: "ئاگرکوژێنەر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Police Officer", ku: "پۆلیس" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "King/Ruler", ku: "پاشا" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Queen", ku: "شاژن" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Crowd", ku: "قەرەباڵغی" }, "hint": { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
    { word: { en: "Customer", ku: "کریار" }, "hint": { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
    { word: { en: "Guest", ku: "میوان" }, "hint": { en: "Group/Role", ku: "کۆمەڵ / ڕۆڵ" } },
    { word: { en: "Manager", ku: "بەڕێوەبەر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Hero", ku: "پاڵەوان" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Villain", ku: "خراپەکار" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Citizen", ku: "هاووڵاتی" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Refugee", ku: "پەنابەر" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Actor", ku: "ئەکتەر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Musician", ku: "مۆسیقاژەن" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Philosopher", ku: "فەیلەسوف" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Poet", ku: "شاعیر" }, "hint": { en: "Job/Profession", ku: "پیشە / کار" } },
    { word: { en: "Daughter", ku: "کچ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Son", ku: "کوڕ" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Niece/Nephew", ku: "برازا / خوشکەزا" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },
    { word: { en: "Relative", ku: "خزم" }, "hint": { en: "Person/Family", ku: "کەس / خێزان" } },

    // --- Places/Buildings/Furniture ---
    { word: { en: "House", ku: "ماڵ / خانوو" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Room", ku: "ژوور" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Door", ku: "دەرگا" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Window", ku: "پەنجەرە" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Table", ku: "مێز" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Chair", ku: "کورسی" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Bed", ku: "سیسەم" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Key", ku: "کلیل" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "City", ku: "شار" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Park", ku: "پارک" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Library", ku: "کتێبخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Kitchen", ku: "چێشتخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Garden", ku: "باخچە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Street", ku: "شەقام" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Office", ku: "ئۆفیس" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Shop/Store", ku: "دوکان" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Market", ku: "بازاڕ" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Floor (Ground)", ku: "زەوی" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Stairs", ku: "قادرمە" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Sofa/Couch", ku: "قەنەفە" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Rug/Carpet", ku: "فەرش" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Curtain", ku: "پەردە" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Pillow", ku: "سەرین" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Cabinet", ku: "کابینە" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Balcony", ku: "باڵکۆن" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Basement", ku: "ژێرزەمین" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Apartment", ku: "شوقە" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Palace", ku: "کۆشک" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Castle", ku: "قەڵا" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },
    { word: { en: "Tent", ku: "چادر" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Vase", ku: "گوڵدان" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Picture Frame", ku: "چوارچێوەی وێنە" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Candle", ku: "مۆم" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Hotel", ku: "هۆتێل" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Restaurant", ku: "چێشتخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Theater", ku: "شانۆ" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Stadium", ku: "یاریگا" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Mosque", ku: "مزگەوت" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Church", ku: "کەنیسە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Factory", ku: "کارگە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Attic", ku: "سەربان" }, "hint": { en: "Place/Home", ku: "شوێن / ماڵ" } },

    // --- Food/Drink/Ingredients ---
    { word: { en: "Water", ku: "ئاو" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Bread", ku: "نان" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Milk", ku: "شیر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Meat", ku: "گۆشت" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Apple", ku: "سێو" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Orange (Fruit)", ku: "پڕتەقاڵ" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Salt", ku: "خوێ" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Sugar", ku: "شەکر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Tea", ku: "چا" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Egg", ku: "هێلکە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Rice", ku: "برنج" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Cheese", ku: "پەنیر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Honey", ku: "هەنگوین" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Flour", ku: "ئارد" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Butter", ku: "کەرە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Cake", ku: "کێک" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Soup", ku: "شۆربا" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Grape", ku: "ترێ" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Fish (Food)", ku: "ماسی" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Vegetable", ku: "سەوزە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Chicken (Food)", ku: "گۆشتی مریشک" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Potato", ku: "پەتاتە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Tomato", ku: "تەماتە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Onion", ku: "پیاز" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Garlic", ku: "سیر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Salad", ku: "زەڵاتە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Yogurt", ku: "ماست" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Juice", ku: "شەربەت" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Beer", ku: "بیرە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Wine", ku: "شەراب" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Chocolate", ku: "شوکولاتە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Cookie", ku: "کێکی بچووک" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Ice Cream", ku: "گولێنە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Sandwich", ku: "ساندویچ" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Pasta", ku: "پاستا" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Lemon", ku: "لیمۆ" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Banana", ku: "مۆز" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Cucumber", ku: "خەیار" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Pepper (Spice)", ku: "بیبەر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Vinegar", ku: "سرکە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Oil (Cooking)", ku: "زەیت" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Grill/BBQ", ku: "کباب" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Dough", ku: "هەویر" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Sausage", ku: "سجق" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Jam", ku: "مورەبا" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Syrup", ku: "شیلە" }, "hint": { en: "Food/Drink", ku: "خواردن / خواردنەوە" } },
    { word: { en: "Oven", ku: "فڕن" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },
    { word: { en: "Kettle", ku: "غەوری" }, "hint": { en: "Object/Item", ku: "شت / کەلوپەل" } },

    // --- Nature/Weather/Space ---
    { word: { en: "Sun", ku: "خۆر" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Moon", ku: "مانگ" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Star", ku: "ئەستێرە" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Air", ku: "هەوا" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Fire", ku: "ئاگر" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Tree", ku: "دار" }, "hint": { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
    { word: { en: "Flower", ku: "گوڵ" }, "hint": { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
    { word: { en: "Rain", ku: "باران" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Snow", ku: "بەفر" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Wind", ku: "با" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Cloud", ku: "هەور" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "River", ku: "ڕووبار" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Lake", ku: "دەریاچە" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Stone", ku: "بەرد" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Earth/Ground", ku: "زەوی" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Grass", ku: "گیا" }, "hint": { en: "Nature/Plant", ku: "سروشت / ڕووەک" } },
    { word: { en: "Desert", ku: "بیابان" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Fog", ku: "تەم" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Ice", ku: "بەستەڵەک" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Dust", ku: "تۆز" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Valley", ku: "دۆڵ" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Forest", ku: "دارستان" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Cave", ku: "ئەشکەوت" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Volcano", ku: "گڕکان" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Tornado", ku: "گەردەلول" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Lightning", ku: "هەورەبروسکە" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Thunder", ku: "هەورەگرمە" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Wave", ku: "شەپۆل" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Sand", ku: "خۆڵ" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Soil", ku: "خاک" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Pebble", ku: "چەو" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Island", ku: "دوورگە" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Peninsula", ku: "نیمچە دوورگە" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Jungle", ku: "جەنگەڵ" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Swamp", ku: "زەلکاو" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Waterfall", ku: "تاڤگە" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Rainbow", ku: "پەلکەزێڕینە" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Galaxy", ku: "گەردوون" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Planet", ku: "هەسارە" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Comet", ku: "کلکدار" }, "hint": { en: "Nature/Weather", ku: "سروشت / کەشوهەوا" } },
    { word: { en: "Steam/Vapor", ku: "هەڵم" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Coal", ku: "خەڵوز" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Crystal", ku: "کریستاڵ" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Mud", ku: "قوڕ" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },
    { word: { en: "Petroleum", ku: "نەوت" }, "hint": { en: "Material/Element", ku: "ماددە / توخم" } },

    // --- Animals/Insects ---
    { word: { en: "Dog", ku: "سەگ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Cat", ku: "پشیلە" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Bird", ku: "باڵندە" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Cow", ku: "مانگا" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Horse", ku: "ئەسپ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Lion", ku: "شێر" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Snake", ku: "مار" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Tiger", ku: "پڵنگ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Mouse", ku: "مشک" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Sheep", ku: "مەڕ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Goat", ku: "بزن" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Chicken", ku: "مریشک" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Elephant", ku: "فیل" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Wolf", ku: "گورگ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Bear", ku: "ورچ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Rabbit", ku: "کەروێشک" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Donkey", ku: "کەر" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Spider", ku: "جاڵجاڵۆکە" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Dolphin", ku: "دەڵفین" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Whale", ku: "نەهەنگ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Shark", ku: "قڕش" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Crocodile", ku: "تیمساح" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Kangaroo", ku: "کەنگەر" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Panda", ku: "پاندا" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Giraffe", ku: "زەڕافە" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Eagle", ku: "هەڵۆ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Ostrich", ku: "نەعامە" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Fox", ku: "ڕێوی" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Deer", ku: "ئاسک" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Monkey", ku: "مەیموون" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Frog", ku: "بۆق" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Turtle", ku: "کیسەڵ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Bee", ku: "هەنگ" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Ant", ku: "مێروولە" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Butterfly", ku: "پەپوولە" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Worm", ku: "کرم" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Camel", ku: "وشتر" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Pigeon", ku: "کۆتر" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Owl", ku: "کوندەپەپوو" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Penguin", ku: "بەتریق" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Hedgehog", ku: "ژیشک" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Otter", ku: "سەگاو" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Flamingo", ku: "فلامینگۆ" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },
    { word: { en: "Scorpion", ku: "دووپشک" }, "hint": { en: "Animal/Insect", ku: "ئاژەڵ" } },
    { word: { en: "Octopus", ku: "ئەختەبوت" }, "hint": { en: "Animal", ku: "ئاژەڵ" } },

    // --- Famous/Fictional Figures ---
    { word: { en: "Shakespeare", ku: "شکسپیر" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Einstein", ku: "ئاینشتاین" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Cleopatra", ku: "کلیۆپاترا" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Buddha", ku: "بوودا" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Sherlock Holmes", ku: "شێرلاک هۆڵمز" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Dracula", ku: "دراکیولا" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Genghis Khan", ku: "جەنگیزخان" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Beethoven", ku: "بیتھۆڤن" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Plato", ku: "ئەفلاتوون" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Picasso", ku: "پیکاسۆ" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Queen Elizabeth", ku: "شاژنە ئەلیزابێس" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Mickey Mouse", ku: "میکی ماوس" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Homer Simpson", ku: "هۆمەر سیمپسۆن" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Tarazan", ku: "تەڕەزان" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Newton", ku: "نیوتن" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },

    // --- More Famous Places ---
    { word: { en: "Sahara Desert", ku: "بیابانی سەحرا" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Atlantic Ocean", ku: "زەریای ئەتڵەسی" }, "hint": { en: "Nature/Geography", ku: "سروشت / جوگرافیا" } },
    { word: { en: "Pharaoh", ku: "فیرعەون" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "James Bond", ku: "جەیمس بۆند" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Harry Potter (Character)", ku: "هاری پۆتەر" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Nelson Mandela", ku: "نێڵسن ماندێلا" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Oprah", ku: "ئۆپرا" }, "hint": { en: "Famous Person", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Jack Sparrow", ku: "جاک سپارۆ" }, "hint": { en: "Fictional Character", ku: "کەسایەتی خەیاڵی" } },
    { word: { en: "Saladin", ku: "سەلاحەدین" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Nalî", ku: "نالی" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Goran", ku: "گۆران" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Mustafa Barzani", ku: "مەلا مستەفا بارزانی" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Jalal Talabani", ku: "جەلال تاڵەبانی" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Ibrahim Khalil", ku: "ئیبراھیم خەلیل" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Mala-i Jiziri", ku: "مەلای جزیری" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Cegerxwîn", ku: "جگەرخوێن" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Sherko Bekas", ku: "شێرکۆ بێکەس" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Hasan Zirek", ku: "حەسەن زیرەک" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Adnan Karim", ku: "عەدنان کەریم" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Dildar", ku: "دڵدار" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Chopy Fatah", ku: "چۆپی فەتاح" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },
    { word: { en: "Qazi Muhammad", ku: "قازی محەمەد" }, "hint": { en: "Famous Person (Kurdish/ME)", ku: "کەسی بەناوبانگ" } },

    // --- Body Parts & Health (لەش / تەندروستی) ---
    { word: { en: "Head", ku: "سەر" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Hand", ku: "دەست" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Leg", ku: "قاچ" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Eye", ku: "چاو" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Mouth", ku: "دەڤ" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Nose", ku: "لووت" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Heart", ku: "دڵ" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Stomach", ku: "گەدە" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Blood", ku: "خوێن" }, "hint": { en: "Body Part/Substance", ku: "بەشی لەش/ماددە" } },
    { word: { en: "Bone", ku: "ئێسک" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Sickness", ku: "نەخۆشی" }, "hint": { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
    { word: { en: "Pain", ku: "ئازار" }, "hint": { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
    { word: { en: "Medicine", ku: "دەرمان" }, "hint": { en: "Health/Item", ku: "تەندروستی/کەلوپەل" } },
    { word: { en: "Fever", ku: "تا" }, "hint": { en: "Health/Condition", ku: "تەندروستی/بارودۆخ" } },
    { word: { en: "Muscle", ku: "ماسولکە" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    { word: { en: "Skin", ku: "پێست" }, "hint": { en: "Body Part", ku: "بەشی لەش" } },
    
    // --- Clothing & Accessories (جلوبەرگ / ئامراز) ---
    { word: { en: "Shirt", ku: "کراس" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Pants", ku: "پانتۆڵ" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Dress", ku: "عەزی" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Hat", ku: "کڵاو" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Shoes", ku: "پێڵاو" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Socks", ku: "گۆرەوی" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Jacket", ku: "کۆت" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Ring", ku: "ئەنگوستیلە" }, "hint": { en: "Accessory/Jewelry", ku: "ئامراز/زێڕینگەری" } },
    { word: { en: "Watch", ku: "کاتژمێر" }, "hint": { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
    { word: { en: "Glasses", ku: "چاویلکە" }, "hint": { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
    { word: { en: "Bag", ku: "جانتا" }, "hint": { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
    { word: { en: "Belt", ku: "قایش" }, "hint": { en: "Accessory/Item", ku: "ئامراز/کەلوپەل" } },
    { word: { en: "Scarf", ku: "سروێن" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Gloves", ku: "دەستکێش" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    { word: { en: "Trousers", ku: "تڕاوسەر" }, "hint": { en: "Clothing/Item", ku: "جلوبەرگ/کەلوپەل" } },
    
    // --- Tools & Equipment (ئامراز / کەرەستە) ---
    { word: { en: "Hammer", ku: "چەکوش" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Nail", ku: "بزمار" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Screw", ku: "لوولە" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Axe", ku: "تەور" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Scissors", ku: "مەقەست" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Rope", ku: "ویر" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Ladder", ku: "پەیژە" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Compass", ku: "قیبلە" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Magnet", ku: "موگناتیس" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Battery", ku: "پاتری" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Wire", ku: "تەل" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Microscope", ku: "مایکرۆسکۆپ" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Telescope", ku: "تەلیسکۆپ" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Scale (Weight)", ku: "تەرازوو" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    { word: { en: "Bucket", ku: "سەطل" }, "hint": { en: "Tool/Equipment", ku: "ئامراز/کەرەستە" } },
    
    // --- Abstract Concepts & Time (چەمک / کات / سۆز) ---
    { word: { en: "Time", ku: "کات" }, "hint": { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Day", ku: "ڕۆژ" }, "hint": { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Year", ku: "ساڵ" }, "hint": { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Idea", ku: "بیرۆکە" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Truth", ku: "ڕاستی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Lie", ku: "درۆ" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Love", ku: "خۆشەویستی" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Hate", ku: "ڕق" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Hope", ku: "هیواداری" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Fear", ku: "ترس" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Peace", ku: "ئاشتی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "War", ku: "شەڕ" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Freedom", ku: "ئازادی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Justice", ku: "دادپەروەری" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Rule/Law", ku: "یاسا" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "History", ku: "مێژوو" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Future", ku: "داهاتوو" }, "hint": { en: "Abstract Concept/Time", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Dream", ku: "خەون" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Wisdom", ku: "دانایی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Art", ku: "هونەر" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Music", ku: "مۆسیقا" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Silence", ku: "بێدەنگی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },

    // --- Verbs (کردار) ---
    { word: { en: "Run", ku: "ڕاکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Sleep", ku: "خەوتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Eat", ku: "خواردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Talk", ku: "قسەکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Walk", ku: "ڕۆیشتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Jump", ku: "بازدان" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Swim", ku: "مەلەکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Write", ku: "نووسین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Read", ku: "خوێندنەوە" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "See", ku: "بینین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Hear", ku: "بیستن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Think", ku: "بیرکردنەوە" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Know", ku: "زانین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Give", ku: "پێدان" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Take", ku: "بردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Come", ku: "هاتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Go", ku: "ڕۆیشتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Cry", ku: "گریان" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Laugh", ku: "پێکەنین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Dance", ku: "سەماکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Sing", ku: "گۆرانی وتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },

    // --- Technology & Digital World (تەکنەلۆجیا / جیهانی دیجیتاڵ) ---
    { word: { en: "Computer", ku: "کۆمپیوتەر" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Internet", ku: "ئینتەرنێت" }, "hint": { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
    { word: { en: "Keyboard", ku: "کیبۆرد" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Mouse (Computer)", ku: "ماوس" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Camera", ku: "کامێرا" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Robot", ku: "ڕۆبۆت" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Screen", ku: "شاشە" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    { word: { en: "Website", ku: "ماڵپەڕ" }, "hint": { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
    { word: { en: "Program/App", ku: "بەرنامە" }, "hint": { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
    { word: { en: "Data", ku: "داتا" }, "hint": { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
    { word: { en: "Email", ku: "ئیمەیل" }, "hint": { en: "Technology/Concept", ku: "تەکنەلۆجیا/چەمک" } },
    { word: { en: "Cable", ku: "کێبڵ" }, "hint": { en: "Technology/Object", ku: "تەکنەلۆجیا/شت" } },
    
    // --- Places & Infrastructure (شوێن و ژێرخانی ئابووری) ---
    { word: { en: "Bank", ku: "بانک" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Museum", ku: "مۆزەخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Airport", ku: "فڕۆکەخانە" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Train Station", ku: "وێستگەی شەمەندەفەر" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Bridge", ku: "پرد" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Tunnel", ku: "تونێل" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Road", ku: "ڕێگا" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Zoo", ku: "باخچەی ئاژەڵان" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Stadium", ku: "یاریگا" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    { word: { en: "Harbor/Port", ku: "بەندەر" }, "hint": { en: "Place/Building", ku: "شوێن / باڵەخانە" } },
    
    // --- Abstract Concepts & Emotion (چەمک / دەربڕین / وشە / سۆز) ---
    { word: { en: "Money", ku: "پارە" }, "hint": { en: "Abstract Concept/Item", ku: "چەمک / دەربڕین / وشە/کەلوپەل" } },
    { word: { en: "Wealth", ku: "سامان" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Poverty", ku: "هەژاری" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Happiness", ku: "بەختەوەری" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Sadness", ku: "خەمباری" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Anger", ku: "تووڕەیی" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Surprise", ku: "سەرسوڕمان" }, "hint": { en: "Emotion/Feeling", ku: "سۆز/هەست" } },
    { word: { en: "Beauty", ku: "جوانی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Ugliness", ku: "ناشرینی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Difficulty", ku: "زەحمەتی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Ease", ku: "ئاسانی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "System", ku: "سیستەم" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Religion", ku: "ئایین" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Philosophy", ku: "فەلسەفە" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },
    { word: { en: "Silence", ku: "بێدەنگی" }, "hint": { en: "Abstract Concept", ku: "چەمک / دەربڕین / وشە" } },

    // --- Actions & Verbs (کردار) ---
    { word: { en: "Cook (Action)", ku: "چێشت لێنان" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Drive", ku: "لێخوڕین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Teach", ku: "فێرکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Learn", ku: "فێربوون" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Buy", ku: "کڕین" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Sell", ku: "فرۆشتن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Help", ku: "یارمەتیدان" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Wait", ku: "چاوەڕێ کردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Travel", ku: "گەشتکردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Remember", ku: "بیر هێنانەوە" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Forget", ku: "لەبیر کردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Build", ku: "دروست کردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Destroy", ku: "وێران کردن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Win", ku: "بردنەوە" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    { word: { en: "Lose", ku: "دۆڕاندن" }, "hint": { en: "Action/Verb", ku: "کردار" } },
    
    // --- Adjectives & Adverbs (سیفەت / شێوەکار) ---
    { word: { en: "Beautiful", ku: "جوان" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Ugly", ku: "ناشرین" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Fast", ku: "خێرا" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Slow", ku: "هێواش" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "High", ku: "بەرز" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Low", ku: "نزم" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Empty", ku: "بەتاڵ" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Full", ku: "پڕ" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Rich", ku: "دەوڵەمەند" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Poor", ku: "هەژار" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Happy", ku: "دڵخۆش" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Sad", ku: "خەمبار" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Angry", ku: "تووڕە" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "New", ku: "نوێ" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Old", ku: "کۆن" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Loud", ku: "بەرز (دەنگ)" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Quiet", ku: "هێمن" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Strong", ku: "بەهێز" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Weak", ku: "لاواز" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Big", ku: "گەورە" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } },
    { word: { en: "Small", ku: "بچووک" }, "hint": { en: "Adjective/Descriptor", ku: "سیفەت/وەسفکار" } }
];
